sprite $helm [100x100/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEDDDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEDDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDDEEFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFEEDDEEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEEEDEDEFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFEDEDDEDFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDEEEFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFEDEEDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDEDEFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDEEEFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFEDDDDDDDDDDFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDEEEFFFFFFFFFFFFFFFFFFFFEDDDDDDDDFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDDDEEFFFFFFFFFFFEEEDDDDDEDDDDDDDEDDDEEEFFFFFFFFFFFFFEDDDDDDDDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEEDDDDDDDDDEDFFFFFFFFEEDDEEDDDDDDDDDDDDDDDDEEEDDEEFFFFFFFFFFDEDDDDDDDDDDDFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDDDDDDDDDDEEFFFFEEDEEDDDDDDDDDDDDDDDDDDDDDDDDDEEDEEFFFFFFEEDDDDDDDDDDEEFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDDDDDDDDDDEEFEDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDEFFFFEDDDDDDDDDDDDFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEDDDDDDDDDDDDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDEEEDDDDDDDDDDDEEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEEDDDDDDDDDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDEDDDDDDDDDDEEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFDEDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEDEDDDDDDDDDDDDDDDDDDDEEDDDDDEEEEEDDDDDEEDDDDDDDDDDDDDDDDDDDDDEDEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEEEDDDDDDDDDDDDDDDEDDEEEEEDFFFFFFFFFEDEEDDEDDDDDDDDDDDDDDDDDEDEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEDDDDDDDDDDDDDDEDDEEFFFFFFFFFFFFFFFFFFFFFEEDDEDDDDDDDDDDDDDEDEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEEDDDDDDDDDDDDEDEEEFFFFFFFFFFFFFFFFFFFFFFFFFEEEDEDDDDDDDDDDDDEEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEEDDDDDDDDDDDEDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEDEDDDDDDDDDDDEEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEEDDDDDDDDDDDEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEEEDDDDDDDDDDEEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDDDDDDDDDDEDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDDDEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDDDDDDDDDDEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDEEDDDDDDDDDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDDDDDDDDDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEEDDDDDDDDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDEEEEEEEEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEEEEEEEEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDEFFFFFFFFFFFFFFFFFFDDDD
DDDDDDDEFFFFFFEDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDEFFFFFFFFFFFFFFFFEDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDEFFFFFFFFFFFFFEEEDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDEEDFFFFFFFFFFFEDEDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDEDEFFFFFFFFEDEDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDEDEFFFFFFEEDDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDEDEFFFEDEDDDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDEDDDDDDDEEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDDDEEFEDEDDDDDDDDDD
DDDDDDDEDDDDDDDDDDDDDDFFFFFFDDDDDDDEDDDDDDDEEFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDDDDEDCDDDDDDDDDDDD
DDDDDDDEDDDDDDDDDDDDDDFFFFFFDDDDDDDEDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDDDDDEDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDFFFFFFDDDDDDDDDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDFFFFFFDDDDDDDDDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDFFFFFFDDDDDDDDDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDFFFFFFDDDDDDDDDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDEDDDDDDDDDDDEDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDFFFFFFDDDDDDDDDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDEEDDDDDDDDDEEDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDFFFFFFDDDDDDDDDDDDDDDEFFFFFFEDDDDDDDEFFFFFFFFFFFFFFDDDDDDDEEEDDDDDDDEDEDDDDDDD
DDDDDDDEDDDDDDDDDDDDDDFFFFFFDDDDDDDEDDDDDDDEFFFFFFEDDDDDDDDEEEEEEEEFFFFFFDDDDDDDEFE9EDDDDDDEEDDDDDDD
DDDDDDDEEEEEEEDDDDDDDDFFFFFFDDDDDDDEEEEEEEEEEFFFFFEDDDDDDDEEEEEEEEEFFFFFFDDDDDDDEFFEDEDDEDEFEDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDEEEEEEEEEEFFFFFEDDDDDDDDDDDDDDDDFFFFFFDDDDDDDEFFFEDEDEFFFEDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDDDDDDDDDDFFFFFFDDDDDDDEFFFFEEEFFFFEDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDDDDDDDDDDFFFFFFDDDDDDDEFFFFFFFFFFFEDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDDDDDDDDDDFFFFFFDDDDDDDEFFFFFFFFFFFEDDDDDDD
DDDDDDDEFFFFFFDDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDDDDDDDDDDFFFFFFDDDDDDDEFFFFFFFFFFFEDDDDDDD
DDDDDDDEFFFFFFEDDDDDDDFFFFFFDDDDDDDDDDDDDDDDEFFFFFEDDDDDDDDDDDDDDDDFFFFFFDDDDDDDEFFFFFFFFFFFEDDDDDDD
EEEEEEEDFFFFFFEEEEEEEEFFFFFFEEEEEEEEEEEEEEEEEFFFFFEEEEEEEEEEEEEEEEEFFFFFFEEEEEEEEFFFFFFFFFFFEEEEEEEE
EEEEEEEDFFFFFFEEEEEEEEFFFFFFEEEEEEEEEEEEEEEEEFFFFFEEEEEEEEEEEEEEEEEFFFFFFEEEEEEEEFFFFFFFFFFFEEEEEEEE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDDDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDDDDDDDDEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEDDDDDDDDEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDDDDDDDDDEDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDDDEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDDDDDDDDDDDDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDDEEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEEEDDDDDDDDDDEDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEEDDDDDDDDDDDEEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEEDDDDDDDDDDDDEDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEDEDDDDDDDDDDDEEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEEDDDDDDDDDDDDDEDEEFFFFFFFFFFFFFFFFFFFFFFFFFEEDDEDDDDDDDDDDDDEEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDDDDDDEDEEEFFFFFFFFFFFFFFFFFFFEEEDEDDDDDDDDDDDDDDDDEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDDDDDDDDEEDDEEDEFFFFFFFFFEEEEDDEEDDDDDDDDDDDDDDDDDDEEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFEDDDDDDDDDDDDDDDDDDDDDDEEDDDDDDDDDDDDDEEDDDDDDDDDDDDDDDDDDDDDDDEEFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEDDDDDDDDDDDFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEEDDDDDDDDDDEEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEDDDDDDDDDDEEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEDEFEEDDDDDDDDDDEEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEDDDDDDDDDDEEFEDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEDDEFFFFEDDDDDDDDDDDDFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEDDDDDDDDDDEEFFFFEEDDEEDDDDDDDDDDDDDDDDDDDDDDDDEDDEEFFFFFFEEDDDDDDDDDDEEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDDDEDFFFFFFFFDEEDDEEEDDDDDDDDDDDDDDEEDDDEEDFFFFFFFFFEEDDDDDDDDDDCFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDDEDEFFFFFFFFFFFFEEEDDDDEDDDDDDDEDDEEEFFFFFFFFFFFFFFFDEDDDDDDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDDEEFFFFFFFFFFFFFFFFFFFDEDDDDDDDDEFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDDFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDDFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFEDEDDDDDDDFFFFFFFFFFFF
FFFFFFFFFFFFFFFEDDDDDEDEFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFEEEEDDDDEFFFFFFFFFFFF
FFFFFFFFFFFFFFFEEEEEDEFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFEEDEEEEFFFFFFFFFFFF
FFFFFFFFFFFFFFFFEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFEEEEFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDDDDDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEEDDDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

