sprite $logo_okteto100 [100x96/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666666666666666666676FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666666666666666666666666667FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF7666666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF666666666666666666666666667FFFF66666666666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF66666666666666666666667FFFFFFFFFFFF6666666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF6666666666666666666667FFFFFFFFFFFFFFFF66666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF66666666666666666667FFFFFFFFFFFFFFFFFFFF666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF6666666666666666666FFFFFFFFFFFFFFFFFFFFFFF66666666666666666FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFF6666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF66666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF66666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF66666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF6666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF766666666FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7666666666FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF6666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF766666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666667FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666667FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666667FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666667FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF7666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF76666666666FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF6666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666766667FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF66666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF76666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF766666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF6666666666666666676FFFFFFFFFFFFFFFFFFFFFFFF6666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF66666666666666666666FFFFFFFFFFFFFFFFFFFFF666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF666666666666666666666FFFFFFFFFFFFFFFFFF6666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF76666666666666666666666FFFFFFFFFFFFFF666666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF666666666666666666666666FFFFFFFFF666666666666666666666667FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF76666666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF666666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF7666666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66466666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF66666666666666666666666666666667FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7666666666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6666666666666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7766666666666666FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFCCCCCCCCFFFFFFFCCCCCFFFFFFFFFFFFFCCCCCFFFFFFFFFFCCCCCCCCFFFFFFFFFCCCCCFFFFFFFFFFFCCCCCCCFFFFFF
FFFFCCCCCCCCCCCCFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCFFFCCCCCCCCCCCCFFFFCCCCCCCCCCCCCFFFCCCCCCCCCCCCFFFF
FFFCCCCCCCCCCCCCCFFFFCCCCCFFFCCCCCCCCCCCCCCCCCCCCFFCCCCCCCCCCCCCCCFFCCCCCCCCCCCCCFFCCCCCCCCCCCCCCCFF
FFCCCCCCCCCCCCCCCCFFFCCCCCFFCCCCCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCFCCCCCCCCCCCCCCCCCF
FCCCCCCCCCCCCCCCCCCFFCCCCCFFCCCCCCCCCCCCCCCCCCCCCFBCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF
CCCCCCCCCCCCCCCCCCCCFCCCCCFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCCFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCFFCCCCCCCCCCCCCCCCCCCCCFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCFFFFFCCCCCCCCFCCCCCCCCCCCCCFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCCCCFFFFFCCCCCCC
CCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCCFFFFFFFFCCCCCC
CCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCCFFFFFFFFFCCCCC
CCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCFFFFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCFFFFFFFFFFCCCCC
CCCCCFFFFFFFFFFCCCCCCCCCCCCCCCCCFFFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCFFFFFFFFFFCCCCC
CCCCCFFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCCFFFFFFFFFCCCCC
CCCCCCFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFCCCCCFFFFCCCCCCCCCCCCCCCCCCCCCFFCCCCCFFFFCCCCCCCFFFFFFFCCCCCC
CCCCCCCFFFFFCCCCCCCCFCCCCCCCCCCCCCFFFFFCCCCCCFFFCCCCCCCCFFFFFFCCCCCCCFFCCCCCCFFFCCCCCCCCFFFFFCACCCCC
CCCCCCCCCCCCCCCCCCCCFCCCCCCCCCCCCCCFFFFCCCCCCCCCCCCCCCCCCCFFCCCCCCCCCFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCFCCCCCFCCCCCCCCCFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCFFCCCCCFCCCCCCCCCFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FCCCCCCCCCCCCCCCCCCFFCCCCCFFCCCCCCCCCFFCCCCCCCCCCFCCCCCCCCCCCCCCCCCCFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCF
FFCCCCCCCCCCCCCCCCFFFCCCCCFFFCCCCCCCCFFCCCCCCCCCCFCCCCCCCCCCCCCCCCCFFFFCCCCCCCCCCFCCCCCCCCCCCCCCCCCF
FFFCCCCCCCCCCCCCCFFFFCCCCCFFFFCCCCCCCFFFCCCCCCCCCFFCCCCCCCCCCCCCCCFFFFFFCFCCCCCCCFFCCBCCCCCCCCCCCFFF
}

!define LOGO_OKTETO100(_color)                                 SPRITE_PUT(                                  logo_okteto100, _color)
!define LOGO_OKTETO100(_color, _scale)                         SPRITE_PUT(                                  logo_okteto100, _color, _scale)
!define LOGO_OKTETO100(_color, _scale, _alias)                 SPRITE_ENT(  _alias, LOGO OKTETO100,         logo_okteto100, _color, _scale)
!define LOGO_OKTETO100(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, LOGO OKTETO100,         logo_okteto100, _color, _scale, _shape)
!define LOGO_OKTETO100(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, LOGO OKTETO100, _label, logo_okteto100, _color, _scale, _shape)
skinparam folderBackgroundColor<<LOGO OKTETO100>> White
